import { createBlankEvent, menuItem, uid } from "./event-factory";
import type { EventRecord } from "./types";

function stamp(id: string, code: string, createdAt: string): Pick<
  EventRecord,
  "id" | "code" | "createdAt" | "updatedAt"
> {
  return { id, code, createdAt, updatedAt: createdAt };
}

export const SEED_EVENTS: EventRecord[] = [
  createBlankEvent({
    ...stamp("evt-casamento-marina", "CB-2026-0087", "2026-06-12T14:00:00.000Z"),
    title: "Casamento Marina & Rafael",
    type: "casamento",
    status: "confirmado",
    date: "2026-08-29",
    startTime: "18:00",
    endTime: "00:00",
    assemblyTime: "12:00",
    teardownTime: "01:30",
    client: {
      name: "Marina Alves Correia",
      company: "",
      phone: "(85) 98812-4410",
      email: "marina.correia@email.com",
      dayContactName: "Fernanda Alves (irmã)",
      dayContactPhone: "(85) 99931-2208",
    },
    venue: {
      kind: "casa_braga",
      name: "Casa Braga",
      address: "Fortaleza, CE",
      notes: "Cerimônia no jardim, jantar no salão principal. Acesso pela portaria lateral após 16h.",
    },
    guests: { adults: 148, children: 12 },
    serviceStyle: "estacoes",
    uniform: "Social preto, avental terracota na cozinha",
    serviceNotes:
      "Mesa dos noivos com serviço empratado. Demais convidados em estações. Welcome drink no jardim.",
    commercialOwner: "Ítalo Braga",
    operationalOwner: "Helena Castro",
    timeline: [
      { id: uid(), time: "12:00", activity: "Chegada da equipe de montagem e cozinha", owner: "Helena" },
      { id: uid(), time: "14:30", activity: "Início da produção quente", owner: "Chef Lúcio" },
      { id: uid(), time: "17:00", activity: "Welcome drink e canapés no jardim", owner: "Salão" },
      { id: uid(), time: "18:00", activity: "Cerimônia", owner: "Cerimonial" },
      { id: uid(), time: "19:00", activity: "Abertura das estações", owner: "Cozinha" },
      { id: uid(), time: "21:30", activity: "Bolo e brinde", owner: "Confeitaria" },
      { id: uid(), time: "23:30", activity: "Encerramento do serviço de salão", owner: "Salão" },
      { id: uid(), time: "01:30", activity: "Desmontagem e retorno", owner: "Logística" },
    ],
    menu: {
      reception: [
        menuItem("Welcome drink de caju e gengibre", "160 un"),
        menuItem("Canapé de queijo coalho com mel de engenho", "180 un"),
        menuItem("Ceviche de tilápia em colher", "160 un"),
        menuItem("Tartare de tomate com burrata", "140 un", "2 vegetarians extras"),
      ],
      starters: [
        menuItem("Salada tropical com manga e flor de sal", "160 pax"),
        menuItem("Carpaccio de abobrinha com pesto de castanha", "40 pax", "Estação vegetariana"),
      ],
      mains: [
        menuItem("Filé mignon ao molho de vinho tinto", "90 pax"),
        menuItem("Robalo grelhado com manteiga de ervas", "70 pax"),
        menuItem("Risoto de camarão com limão-cravo", "160 pax", "Estação única"),
        menuItem("Nhoque de mandioquinha ao funghi", "30 pax", "Opção vegetariana"),
      ],
      sides: [
        menuItem("Arroz vermelho", "160 pax"),
        menuItem("Legumes assados no forno", "160 pax"),
        menuItem("Farofa de castanha de caju", "160 pax"),
      ],
      desserts: [
        menuItem("Bolo de casamento — baunilha e frutas tropicais", "1 un", "Fornecedor parceiro"),
        menuItem("Cheesecake de maracujá", "80 pax"),
        menuItem("Petit gâteau de chocolate belga", "80 pax"),
      ],
      kids: [
        menuItem("Mini hambúrguer", "12 un"),
        menuItem("Batata rústica", "12 pax"),
        menuItem("Brigadeiro de colher", "24 un"),
      ],
      drinks: [
        menuItem("Água com e sem gás", "10 cx"),
        menuItem("Refrigerantes", "8 cx"),
        menuItem("Suco de caju e acerola", "20 L"),
        menuItem("Open bar contratado à parte", "", "Fornecedor do cliente"),
      ],
      dietaryNotes:
        "4 vegetarianos confirmados. 1 convidada celíaca (mesa 7, nome: Paula Nunes). Sem amendoim em nenhuma preparação.",
      kitchenNotes:
        "Risoto sai em dois turnos: 19h10 e 20h20. Filé ao ponto malpassado na mesa dos noivos. Reservar 8 pratos vegetarianos extras.",
    },
    staff: [
      { id: uid(), role: "Chef", name: "Lúcio Menezes", quantity: 1, kind: "interna", shift: "12:00–01:00", dailyRate: 0 },
      { id: uid(), role: "Confeiteira", name: "Rita Lopes", quantity: 1, kind: "interna", shift: "14:00–23:00", dailyRate: 0 },
      { id: uid(), role: "Auxiliar de cozinha", name: "", quantity: 4, kind: "interna", shift: "12:00–01:00", dailyRate: 0 },
      { id: uid(), role: "Garçom", name: "", quantity: 10, kind: "externa", shift: "16:00–00:30", dailyRate: 180 },
      { id: uid(), role: "Copeira", name: "", quantity: 3, kind: "externa", shift: "16:00–00:30", dailyRate: 150 },
      { id: uid(), role: "Maitre", name: "Paulo Henrique", quantity: 1, kind: "interna", shift: "16:00–00:30", dailyRate: 0 },
    ],
    materials: [
      { id: uid(), name: "Prato raso branco", quantity: 180, unit: "un", source: "estoque", notes: "" },
      { id: uid(), name: "Taça de água", quantity: 180, unit: "un", source: "estoque", notes: "" },
      { id: uid(), name: "Rechaud grande", quantity: 6, unit: "un", source: "estoque", notes: "" },
      { id: uid(), name: "Toalha off-white", quantity: 22, unit: "un", source: "estoque", notes: "Troca reserva: 4" },
      { id: uid(), name: "Cadeiras Tiffany", quantity: 160, unit: "un", source: "aluguel", notes: "Fornecedor Aludecor" },
    ],
    vehicles: [
      { id: uid(), vehicle: "Sprinter branca", driver: "Cicero", departure: "11:30", returnTime: "02:00", purpose: "Cozinha e louças" },
      { id: uid(), vehicle: "Fiorino", driver: "Jonas", departure: "13:00", returnTime: "01:00", purpose: "Complementos e gelo" },
    ],
    finance: {
      contractValue: 48600,
      paid: 24300,
      paymentNotes: "Sinal 50% recebido em 12/06. Saldo até 22/08.",
    },
    briefing:
      "Casamento clássico com toque regional. Família valoriza pontualidade do jantar e apresentação das estações. Cerimonial: Casa Amora.",
    attentionPoints:
      "Tia da noiva é alérgica a camarão — não circular risoto na mesa 4. Chuva: cerimônia migra para o salão, canapés no hall.",
  }),
  createBlankEvent({
    ...stamp("evt-coffee-bnb", "CB-2026-0084", "2026-07-28T11:00:00.000Z"),
    title: "Coffee break — Encontro de Gestores BNB",
    type: "coffee",
    status: "em_preparacao",
    date: "2026-08-25",
    startTime: "08:30",
    endTime: "12:00",
    assemblyTime: "07:00",
    teardownTime: "12:30",
    client: {
      name: "Assessoria de Eventos BNB",
      company: "Banco do Nordeste",
      phone: "(85) 3299-3000",
      email: "eventos@bnb.gov.br",
      dayContactName: "Carla Pinheiro",
      dayContactPhone: "(85) 98700-1192",
    },
    venue: {
      kind: "externo",
      name: "Hotel Gran Marquise — Salão Iracema",
      address: "Av. Beira Mar, 3980 — Mucuripe, Fortaleza",
      notes: "Carga pela rampa de serviço. Credenciamento até 06:50.",
    },
    guests: { adults: 80, children: 0 },
    serviceStyle: "coffee",
    uniform: "Social Casa Braga",
    serviceNotes: "Montagem em ilha única. Reposição contínua até 11h30.",
    commercialOwner: "Ítalo Braga",
    operationalOwner: "Helena Castro",
    timeline: [
      { id: uid(), time: "07:00", activity: "Chegada e montagem", owner: "Equipe" },
      { id: uid(), time: "08:20", activity: "Abertura do coffee", owner: "Salão" },
      { id: uid(), time: "10:15", activity: "Reposição completa", owner: "Cozinha" },
      { id: uid(), time: "12:00", activity: "Encerramento e recolha", owner: "Equipe" },
    ],
    menu: {
      reception: [],
      starters: [
        menuItem("Mini quiche de alho-poró", "80 un"),
        menuItem("Wrap de frango desfiado", "80 un"),
        menuItem("Tapioca recheada de queijo coalho", "80 un"),
      ],
      mains: [],
      sides: [],
      desserts: [
        menuItem("Bolo de rolo", "40 fatias"),
        menuItem("Mini cuca de banana", "80 un"),
        menuItem("Frutas da estação", "80 pax"),
      ],
      kids: [],
      drinks: [
        menuItem("Café e leite", "10 L"),
        menuItem("Suco de laranja e caju", "16 L"),
        menuItem("Água", "6 cx"),
      ],
      dietaryNotes: "6 opções vegetarianas sinalizadas. Sem lactose: 2 participantes.",
      kitchenNotes: "Assar quiches no hotel. Levar forno auxiliar.",
    },
    staff: [
      { id: uid(), role: "Chef", name: "Lúcio Menezes", quantity: 1, kind: "interna", shift: "06:40–12:40", dailyRate: 0 },
      { id: uid(), role: "Garçom", name: "", quantity: 4, kind: "externa", shift: "07:00–12:30", dailyRate: 160 },
      { id: uid(), role: "Copeira", name: "", quantity: 1, kind: "externa", shift: "07:00–12:30", dailyRate: 140 },
    ],
    materials: [
      { id: uid(), name: "Xícara de café", quantity: 90, unit: "un", source: "estoque", notes: "" },
      { id: uid(), name: "Prato de sobremesa", quantity: 90, unit: "un", source: "estoque", notes: "" },
      { id: uid(), name: "Rechaud pequeno", quantity: 3, unit: "un", source: "estoque", notes: "" },
    ],
    vehicles: [
      { id: uid(), vehicle: "Sprinter branca", driver: "Cicero", departure: "06:20", returnTime: "13:00", purpose: "Montagem completa" },
    ],
    finance: {
      contractValue: 6400,
      paid: 6400,
      paymentNotes: "Faturado e pago via empenho.",
    },
    briefing: "Evento institucional. Comunicação visual do banco já no salão. Não usar peças com outras marcas.",
    attentionPoints: "Horário rígido. Credenciamento do hotel exige lista de equipe até segunda.",
  }),
  createBlankEvent({
    ...stamp("evt-aniversario-zelia", "CB-2026-0082", "2026-07-02T16:20:00.000Z"),
    title: "Aniversário 60 anos — Zélia Mendes",
    type: "aniversario",
    status: "realizado",
    date: "2026-08-23",
    startTime: "19:00",
    endTime: "23:30",
    assemblyTime: "14:00",
    teardownTime: "00:30",
    client: {
      name: "Ricardo Mendes",
      company: "",
      phone: "(85) 99120-7744",
      email: "ricardo.mendes@email.com",
      dayContactName: "Ricardo Mendes",
      dayContactPhone: "(85) 99120-7744",
    },
    venue: {
      kind: "casa_braga",
      name: "Casa Braga",
      address: "Fortaleza, CE",
      notes: "Salão principal + varanda.",
    },
    guests: { adults: 82, children: 8 },
    serviceStyle: "buffet",
    uniform: "Social Casa Braga",
    serviceNotes: "Buffet clássico. Bolo às 21h.",
    commercialOwner: "Ítalo Braga",
    operationalOwner: "Helena Castro",
    timeline: [
      { id: uid(), time: "14:00", activity: "Montagem", owner: "Equipe" },
      { id: uid(), time: "19:00", activity: "Recepção e canapés", owner: "Salão" },
      { id: uid(), time: "20:00", activity: "Abertura do buffet", owner: "Cozinha" },
      { id: uid(), time: "21:00", activity: "Bolo e parabéns", owner: "Confeitaria" },
    ],
    menu: {
      reception: [
        menuItem("Canapé de pasta de alcachofra", "90 un"),
        menuItem("Mini esfirra de carne", "90 un"),
      ],
      starters: [menuItem("Mesa de frios e queijos", "90 pax")],
      mains: [
        menuItem("Lasanha à bolonhesa", "90 pax"),
        menuItem("Strogonoff de frango", "90 pax"),
        menuItem("Arroz de forno", "90 pax"),
      ],
      sides: [menuItem("Batata sauté", "90 pax"), menuItem("Salada verde", "90 pax")],
      desserts: [menuItem("Bolo de chocolate com morango", "1 un"), menuItem("Pudim de leite", "90 pax")],
      kids: [menuItem("Nuggets e batata", "8 pax")],
      drinks: [menuItem("Refrigerante e suco", "10 cx"), menuItem("Água", "4 cx")],
      dietaryNotes: "2 veganos — lasanha de berinjela reservada.",
      kitchenNotes: "Manter strogonoff em banho-maria baixo para não talhar.",
    },
    staff: [
      { id: uid(), role: "Chef", name: "Lúcio Menezes", quantity: 1, kind: "interna", shift: "14:00–00:00", dailyRate: 0 },
      { id: uid(), role: "Garçom", name: "", quantity: 6, kind: "externa", shift: "17:30–00:00", dailyRate: 170 },
    ],
    materials: [
      { id: uid(), name: "Prato raso", quantity: 100, unit: "un", source: "estoque", notes: "" },
      { id: uid(), name: "Rechaud", quantity: 4, unit: "un", source: "estoque", notes: "" },
    ],
    vehicles: [],
    finance: { contractValue: 12800, paid: 12800, paymentNotes: "Quitado." },
    briefing: "Festa familiar, tom afetivo. Playlist da família.",
    attentionPoints: "Aniversariante chega às 19h20 — canapés já circulando.",
  }),
  createBlankEvent({
    ...stamp("evt-brunch-domingo", "CB-2026-0085", "2026-08-04T09:00:00.000Z"),
    title: "Brunch de domingo na Casa",
    type: "brunch",
    status: "confirmado",
    date: "2026-08-24",
    startTime: "10:00",
    endTime: "14:00",
    assemblyTime: "08:00",
    teardownTime: "15:00",
    client: {
      name: "Casa Braga — operação própria",
      company: "Casa Braga",
      phone: "(85) 99944-1990",
      email: "italo@zoraidebraga.com",
      dayContactName: "Helena Castro",
      dayContactPhone: "(85) 98877-2210",
    },
    venue: casaVenue(),
    guests: { adults: 40, children: 5 },
    serviceStyle: "brunch",
    uniform: "Avental claro",
    serviceNotes: "Serviço contínuo em ilha. Reservas confirmadas até sábado 18h.",
    commercialOwner: "Ítalo Braga",
    operationalOwner: "Helena Castro",
    timeline: [
      { id: uid(), time: "08:00", activity: "Mise en place", owner: "Cozinha" },
      { id: uid(), time: "10:00", activity: "Abertura", owner: "Salão" },
      { id: uid(), time: "14:00", activity: "Encerramento", owner: "Salão" },
    ],
    menu: {
      reception: [],
      starters: [menuItem("Cesta de pães e geleias", "45 pax"), menuItem("Iogurte com granola e manga", "45 pax")],
      mains: [menuItem("Ovos mexidos", "45 pax"), menuItem("Bacalhau à Braga", "45 pax"), menuItem("Tapioca de queijo", "45 pax")],
      sides: [menuItem("Salada de frutas", "45 pax"), menuItem("Bacon e linguiça artesanal", "40 pax")],
      desserts: [menuItem("Bolo de milho", "45 pax"), menuItem("Torta de limão", "45 pax")],
      kids: [menuItem("Panqueca com banana", "5 pax")],
      drinks: [menuItem("Café, suco e prosecco", "45 pax")],
      dietaryNotes: "3 sem glúten — pão de queijo separado.",
      kitchenNotes: "Ovos em lotes pequenos. Bacalhau não pode secar.",
    },
    staff: [
      { id: uid(), role: "Chef", name: "Rita Lopes", quantity: 1, kind: "interna", shift: "07:40–15:00", dailyRate: 0 },
      { id: uid(), role: "Garçom", name: "", quantity: 3, kind: "interna", shift: "09:00–15:00", dailyRate: 0 },
    ],
    materials: [{ id: uid(), name: "Prato de brunch", quantity: 50, unit: "un", source: "estoque", notes: "" }],
    vehicles: [],
    finance: { contractValue: 0, paid: 0, paymentNotes: "Operação própria. Caixa do dia." },
    briefing: "Brunch aberto da casa. Priorizar ritmo calmo e reposição visual.",
    attentionPoints: "Reservas via WhatsApp. Lista na recepção.",
  }),
  createBlankEvent({
    ...stamp("evt-cha-clara", "CB-2026-0088", "2026-08-08T18:00:00.000Z"),
    title: "Chá de bebê — Clara Albuquerque",
    type: "cha",
    status: "confirmado",
    date: "2026-08-30",
    startTime: "16:00",
    endTime: "19:30",
    assemblyTime: "13:30",
    teardownTime: "20:30",
    client: {
      name: "Clara Albuquerque",
      company: "",
      phone: "(85) 98654-0091",
      email: "clara.alb@email.com",
      dayContactName: "Mariana Albuquerque",
      dayContactPhone: "(85) 99221-3345",
    },
    venue: {
      kind: "externo",
      name: "Residência — Meireles",
      address: "Rua Silva Jatahy, 842 — Meireles, Fortaleza",
      notes: "Apartamento cobertura. Elevador de serviço. Sem churrasqueira.",
    },
    guests: { adults: 42, children: 8 },
    serviceStyle: "cocktail",
    uniform: "Social claro",
    serviceNotes: "Finger food circulante + mesa de doces.",
    commercialOwner: "Ítalo Braga",
    operationalOwner: "Helena Castro",
    timeline: [
      { id: uid(), time: "13:30", activity: "Chegada e montagem", owner: "Equipe" },
      { id: uid(), time: "16:00", activity: "Recepção", owner: "Salão" },
      { id: uid(), time: "17:30", activity: "Mesa de doces e chá", owner: "Confeitaria" },
    ],
    menu: {
      reception: [
        menuItem("Mini sanduíche de frango", "80 un"),
        menuItem("Canapé de ricota com geleia de pimenta", "60 un"),
        menuItem("Empada de palmito", "60 un"),
      ],
      starters: [],
      mains: [],
      sides: [],
      desserts: [
        menuItem("Bem-casado", "50 un"),
        menuItem("Macaron", "50 un"),
        menuItem("Bolo naked de baunilha", "1 un"),
      ],
      kids: [menuItem("Pipoca doce", "8 pax")],
      drinks: [menuItem("Chá gelado de hibisco", "10 L"), menuItem("Limonada suíça", "8 L")],
      dietaryNotes: "1 alérgica a ovo — separar empadas e avisar confeitaria.",
      kitchenNotes: "Produção 90% na base. Só montagem no local. Sem fritura no apartamento.",
    },
    staff: [
      { id: uid(), role: "Garçom", name: "", quantity: 3, kind: "externa", shift: "14:00–20:00", dailyRate: 160 },
      { id: uid(), role: "Copeira", name: "", quantity: 1, kind: "externa", shift: "14:00–20:00", dailyRate: 140 },
    ],
    materials: [
      { id: uid(), name: "Prato de sobremesa", quantity: 50, unit: "un", source: "estoque", notes: "" },
      { id: uid(), name: "Suporte de doces", quantity: 4, unit: "un", source: "estoque", notes: "" },
    ],
    vehicles: [
      { id: uid(), vehicle: "Fiorino", driver: "Jonas", departure: "13:00", returnTime: "21:00", purpose: "Montagem leve" },
    ],
    finance: { contractValue: 4200, paid: 2100, paymentNotes: "Saldo no dia, PIX." },
    briefing: "Paleta rosa-areia. Decoração da cliente. Casa só gastronomia e serviço.",
    attentionPoints: "Vizinhos sensíveis a barulho após 19h. Encerrar música baixa.",
  }),
  createBlankEvent({
    ...stamp("evt-coquetel-joia", "CB-2026-0086", "2026-08-01T10:00:00.000Z"),
    title: "Coquetel de lançamento — Joalheria Lumen",
    type: "coquetel",
    status: "em_preparacao",
    date: "2026-08-28",
    startTime: "19:30",
    endTime: "22:30",
    assemblyTime: "16:00",
    teardownTime: "23:30",
    client: {
      name: "Beatriz Lumen",
      company: "Lumen Joias",
      phone: "(85) 98111-7002",
      email: "beatriz@lumenjoias.com",
      dayContactName: "Assessoria Vértice",
      dayContactPhone: "(85) 99712-8800",
    },
    venue: {
      kind: "externo",
      name: "Iate Clube de Fortaleza — Espaço Náutico",
      address: "Av. Pres. Castelo Branco, 3333 — Mucuripe, Fortaleza",
      notes: "Acesso pela portaria 2. Lista de equipe antecipada.",
    },
    guests: { adults: 100, children: 0 },
    serviceStyle: "cocktail",
    uniform: "Social preto",
    serviceNotes: "Somente circulante. Sem mesa de buffet. Passagem a cada 12 minutos.",
    commercialOwner: "Ítalo Braga",
    operationalOwner: "Helena Castro",
    timeline: [
      { id: uid(), time: "16:00", activity: "Montagem da base de apoio", owner: "Equipe" },
      { id: uid(), time: "19:20", activity: "Primeira passagem de canapés", owner: "Salão" },
      { id: uid(), time: "21:00", activity: "Doce e café", owner: "Confeitaria" },
    ],
    menu: {
      reception: [
        menuItem("Ostra com granita de maracujá", "100 un"),
        menuItem("Atum selado com gergelim", "100 un"),
        menuItem("Mini eclair de queijo de cabra", "100 un"),
        menuItem("Espetinho de kafta", "100 un"),
      ],
      starters: [],
      mains: [],
      sides: [],
      desserts: [menuItem("Brownie de chocolate 70%", "100 un"), menuItem("Macaron de pistache", "100 un")],
      kids: [],
      drinks: [menuItem("Água e suco detox", "100 pax", "Bar do clube")],
      dietaryNotes: "Sem frutos do mar para 3 convidados VIP — lista com a assessoria.",
      kitchenNotes: "Ostra só abre às 18h50. Manter gelo constante.",
    },
    staff: [
      { id: uid(), role: "Chef", name: "Lúcio Menezes", quantity: 1, kind: "interna", shift: "15:30–23:30", dailyRate: 0 },
      { id: uid(), role: "Garçom", name: "", quantity: 8, kind: "externa", shift: "18:00–23:00", dailyRate: 190 },
    ],
    materials: [
      { id: uid(), name: "Colher de ceviche", quantity: 120, unit: "un", source: "estoque", notes: "" },
      { id: uid(), name: "Bandeja preta", quantity: 10, unit: "un", source: "estoque", notes: "" },
    ],
    vehicles: [
      { id: uid(), vehicle: "Sprinter branca", driver: "Cicero", departure: "15:20", returnTime: "00:00", purpose: "Base e equipe" },
    ],
    finance: { contractValue: 9800, paid: 4900, paymentNotes: "Saldo contra nota." },
    briefing: "Evento de imagem. Apresentação impecável. Pratos pequenos, muito visuais.",
    attentionPoints: "Vento na varanda — proteger ostras. Coordenar com bar do clube.",
  }),
  createBlankEvent({
    ...stamp("evt-feijoada", "CB-2026-0081", "2026-07-18T13:00:00.000Z"),
    title: "Feijoada de sábado",
    type: "tematico",
    status: "realizado",
    date: "2026-08-22",
    startTime: "12:00",
    endTime: "16:00",
    assemblyTime: "09:00",
    teardownTime: "17:00",
    client: {
      name: "Casa Braga — operação própria",
      company: "Casa Braga",
      phone: "(85) 99944-1990",
      email: "italo@zoraidebraga.com",
      dayContactName: "Helena Castro",
      dayContactPhone: "(85) 98877-2210",
    },
    venue: casaVenue(),
    guests: { adults: 96, children: 14 },
    serviceStyle: "buffet",
    uniform: "Avental terracota",
    serviceNotes: "Feijoada completa em buffet. Caipirinha na entrada.",
    commercialOwner: "Ítalo Braga",
    operationalOwner: "Helena Castro",
    timeline: [
      { id: uid(), time: "09:00", activity: "Início da feijoada", owner: "Cozinha" },
      { id: uid(), time: "12:00", activity: "Abertura do salão", owner: "Salão" },
    ],
    menu: {
      reception: [menuItem("Torresmo e aipim", "110 pax"), menuItem("Caipirinha de caju", "110 un")],
      starters: [menuItem("Couve e laranja", "110 pax")],
      mains: [menuItem("Feijoada completa", "110 pax"), menuItem("Feijoada vegetariana", "12 pax")],
      sides: [menuItem("Arroz branco", "110 pax"), menuItem("Farofa", "110 pax"), menuItem("Vinagrete", "110 pax")],
      desserts: [menuItem("Romeu e Julieta", "110 pax"), menuItem("Pudim de leite", "110 pax")],
      kids: [menuItem("Arroz, feijão sem carne e farofa", "14 pax")],
      drinks: [menuItem("Refrigerante", "8 cx"), menuItem("Suco", "10 L")],
      dietaryNotes: "Feijoada vegetariana identificada em rechaud separado.",
      kitchenNotes: "Feijão no fogo desde sexta 22h. Caldo não pode quebrar.",
    },
    staff: [
      { id: uid(), role: "Chef", name: "Lúcio Menezes", quantity: 1, kind: "interna", shift: "08:00–17:00", dailyRate: 0 },
      { id: uid(), role: "Garçom", name: "", quantity: 6, kind: "externa", shift: "11:00–17:00", dailyRate: 160 },
    ],
    materials: [{ id: uid(), name: "Tigela funda", quantity: 120, unit: "un", source: "estoque", notes: "" }],
    vehicles: [],
    finance: { contractValue: 0, paid: 0, paymentNotes: "Operação própria." },
    briefing: "Clássico da casa. Ritmo alto entre 12h30 e 14h.",
    attentionPoints: "Estoque de laranja e couve — repor às 13h30.",
  }),
  createBlankEvent({
    ...stamp("evt-formatura-ufc", "CB-2026-0091", "2026-08-10T15:00:00.000Z"),
    title: "Formatura Medicina UFC 2026.1",
    type: "formatura",
    status: "rascunho",
    date: "2026-09-05",
    startTime: "20:00",
    endTime: "01:00",
    assemblyTime: "14:00",
    teardownTime: "02:00",
    client: {
      name: "Comissão de Formatura Medicina",
      company: "UFC",
      phone: "(85) 98765-4321",
      email: "comissao.medicina@ufc.br",
      dayContactName: "Ana Beatriz Lima",
      dayContactPhone: "(85) 98765-4321",
    },
    venue: casaVenue("Salão + jardim. Palco no fundo do salão."),
    guests: { adults: 210, children: 10 },
    serviceStyle: "buffet",
    uniform: "Social preto",
    serviceNotes: "Aguardando confirmação final de pax e cardápio B.",
    commercialOwner: "Ítalo Braga",
    operationalOwner: "",
    timeline: [],
    menu: {
      reception: [menuItem("Canapés — cardápio B (a confirmar)", "")],
      starters: [],
      mains: [menuItem("Opção A: estação de carnes", ""), menuItem("Opção B: massa e risoto", "")],
      sides: [],
      desserts: [],
      kids: [],
      drinks: [],
      dietaryNotes: "",
      kitchenNotes: "Não produzir nada até confirmação de 25/08.",
    },
    staff: [],
    materials: [],
    vehicles: [],
    finance: { contractValue: 0, paid: 0, paymentNotes: "Orçamento em fechamento no Comercial." },
    briefing: "Turma grande. Cerimonial próprio. Ainda em conversa de cardápio.",
    attentionPoints: "Não bloquear equipe externa até o contrato assinado.",
  }),
  createBlankEvent({
    ...stamp("evt-jantar-unimed", "CB-2026-0090", "2026-08-06T09:30:00.000Z"),
    title: "Jantar corporativo — Unimed Fortaleza",
    type: "corporativo",
    status: "confirmado",
    date: "2026-09-12",
    startTime: "20:00",
    endTime: "23:00",
    assemblyTime: "16:30",
    teardownTime: "00:00",
    client: {
      name: "Comunicação Unimed",
      company: "Unimed Fortaleza",
      phone: "(85) 4009-9000",
      email: "eventos@unimedfortaleza.com.br",
      dayContactName: "Daniela Rocha",
      dayContactPhone: "(85) 99908-4411",
    },
    venue: {
      kind: "externo",
      name: "Sede Unimed — Auditório Superior",
      address: "Av. Santos Dumont, 2626 — Aldeota, Fortaleza",
      notes: "Cozinha de apoio no 2º andar. Sem fritura no local.",
    },
    guests: { adults: 70, children: 0 },
    serviceStyle: "empratado",
    uniform: "Social preto",
    serviceNotes: "Três tempos empratados. Discurso entre entrada e principal.",
    commercialOwner: "Ítalo Braga",
    operationalOwner: "Helena Castro",
    timeline: [
      { id: uid(), time: "16:30", activity: "Montagem e mise", owner: "Cozinha" },
      { id: uid(), time: "20:00", activity: "Recepção", owner: "Salão" },
      { id: uid(), time: "20:30", activity: "Entrada", owner: "Cozinha" },
      { id: uid(), time: "21:10", activity: "Principal", owner: "Cozinha" },
      { id: uid(), time: "22:10", activity: "Sobremesa", owner: "Confeitaria" },
    ],
    menu: {
      reception: [menuItem("Amuse-bouche de abacaxi e queijo de coalho", "70 un")],
      starters: [menuItem("Tartare de atum com crispy de tapioca", "70 un")],
      mains: [menuItem("Cordeiro com redução de caju", "70 un", "Ponto malpassado padrão")],
      sides: [menuItem("Purê de macaxeira", "70 un"), menuItem("Mini legumes", "70 un")],
      desserts: [menuItem("Espuma de chocolate com flor de sal", "70 un")],
      kids: [],
      drinks: [menuItem("Harmonização do cliente", "", "Sommelier Unimed")],
      dietaryNotes: "2 sem frutos do mar — substituir entrada por carpaccio de abacaxi.",
      kitchenNotes: "Empratamento em linha. 70 pratos em 8 minutos. Testar percurso na quinta.",
    },
    staff: [
      { id: uid(), role: "Chef", name: "Lúcio Menezes", quantity: 1, kind: "interna", shift: "16:00–00:00", dailyRate: 0 },
      { id: uid(), role: "Auxiliar de cozinha", name: "", quantity: 3, kind: "interna", shift: "16:00–00:00", dailyRate: 0 },
      { id: uid(), role: "Garçom", name: "", quantity: 8, kind: "externa", shift: "18:30–23:30", dailyRate: 200 },
    ],
    materials: [
      { id: uid(), name: "Prato de entrada", quantity: 80, unit: "un", source: "estoque", notes: "" },
      { id: uid(), name: "Prato raso", quantity: 80, unit: "un", source: "estoque", notes: "" },
    ],
    vehicles: [
      { id: uid(), vehicle: "Sprinter branca", driver: "Cicero", departure: "15:50", returnTime: "00:20", purpose: "Cozinha empratada" },
    ],
    finance: { contractValue: 18700, paid: 9350, paymentNotes: "Saldo 5 dias antes." },
    briefing: "Jantar de conselho. Discreto, pontual, serviço silencioso.",
    attentionPoints: "Sem fotos da equipe no salão. Crachá obrigatório.",
  }),
  createBlankEvent({
    ...stamp("evt-15-beatriz", "CB-2026-0092", "2026-08-14T17:40:00.000Z"),
    title: "15 anos — Beatriz Fontenele",
    type: "quinze_anos",
    status: "confirmado",
    date: "2026-09-19",
    startTime: "19:30",
    endTime: "01:00",
    assemblyTime: "13:00",
    teardownTime: "02:00",
    client: {
      name: "Patrícia Fontenele",
      company: "",
      phone: "(85) 98840-2255",
      email: "patricia.fontenele@email.com",
      dayContactName: "Patrícia Fontenele",
      dayContactPhone: "(85) 98840-2255",
    },
    venue: casaVenue("Salão principal. Pista no centro."),
    guests: { adults: 90, children: 50 },
    serviceStyle: "buffet",
    uniform: "Social Casa Braga",
    serviceNotes: "Menu adulto + kids reforçado. Bolo 22h.",
    commercialOwner: "Ítalo Braga",
    operationalOwner: "Helena Castro",
    timeline: [
      { id: uid(), time: "13:00", activity: "Montagem", owner: "Equipe" },
      { id: uid(), time: "19:30", activity: "Valsa e recepção", owner: "Cerimonial" },
      { id: uid(), time: "20:30", activity: "Buffet", owner: "Cozinha" },
      { id: uid(), time: "22:00", activity: "Bolo", owner: "Confeitaria" },
    ],
    menu: {
      reception: [menuItem("Salgados fritos e assados", "300 un"), menuItem("Canapé doce de morango", "140 un")],
      starters: [menuItem("Mesa de frios", "140 pax")],
      mains: [menuItem("Penne ao molho branco", "140 pax"), menuItem("Frango grelhado com ervas", "140 pax")],
      sides: [menuItem("Arroz", "140 pax"), menuItem("Batata gratinada", "140 pax")],
      desserts: [menuItem("Bolo de 15 anos", "1 un"), menuItem("Mesa de doces finos", "140 pax")],
      kids: [menuItem("Hot dog", "50 un"), menuItem("Batata frita", "50 pax"), menuItem("Pipoca gourmet", "50 pax")],
      drinks: [menuItem("Refrigerante e suco", "16 cx"), menuItem("Água", "8 cx")],
      dietaryNotes: "Criança alérgica a leite (mesa kids, nome: Gael).",
      kitchenNotes: "Fritura controlada. Separar lote kids sem lácteos.",
    },
    staff: [
      { id: uid(), role: "Chef", name: "Rita Lopes", quantity: 1, kind: "interna", shift: "13:00–02:00", dailyRate: 0 },
      { id: uid(), role: "Garçom", name: "", quantity: 8, kind: "externa", shift: "18:00–01:30", dailyRate: 180 },
      { id: uid(), role: "Monitor kids", name: "", quantity: 2, kind: "externa", shift: "19:00–00:30", dailyRate: 150 },
    ],
    materials: [
      { id: uid(), name: "Prato raso", quantity: 160, unit: "un", source: "estoque", notes: "" },
      { id: uid(), name: "Taça de suco", quantity: 160, unit: "un", source: "estoque", notes: "" },
    ],
    vehicles: [],
    finance: { contractValue: 21400, paid: 10700, paymentNotes: "Saldo até 12/09." },
    briefing: "Decoração rosa-chá da cliente. DJ próprio. Casa: gastronomia e serviço.",
    attentionPoints: "Pista ocupa 12 lugares — ajustar mesas. Alergia do Gael na ficha da cozinha.",
  }),
];

function casaVenue(notes = ""): EventRecord["venue"] {
  return {
    kind: "casa_braga",
    name: "Casa Braga",
    address: "Fortaleza, CE",
    notes,
  };
}
