import { createBlankEvent, menuItem } from "./event-factory";
import { emptyStaff, type EventRecord, type MenuItem } from "./types";

function stamp(id: string, code: string, createdAt: string): Pick<
  EventRecord,
  "id" | "code" | "createdAt" | "updatedAt"
> {
  return { id, code, createdAt, updatedAt: createdAt };
}

function items(...rows: [string, string, string?][]): MenuItem[] {
  return rows.map(([name, quantity, notes = ""]) => menuItem(name, quantity, notes));
}

export const SEED_EVENTS: EventRecord[] = [
  createBlankEvent({
    ...stamp("evt-casamento-marina", "CB-2026-0087", "2026-06-12T14:00:00.000Z"),
    title: "Casamento Marina & Rafael",
    type: "casamento",
    status: "confirmado",
    date: "2026-08-29",
    materialDeliveryDate: "2026-08-28",
    foodDeliveryDate: "2026-08-29",
    perCapita: 280,
    venue: {
      kind: "casa_braga",
      name: "Casa Braga",
      address: "Casa Braga — Fortaleza, CE. Cerimônia no jardim, jantar no salão.",
    },
    guests: { adults: 148, children: 12, professionals: 8 },
    teamArrival: "12:00",
    invitationTime: "17:00",
    serviceTime: "19:00",
    staff: {
      garcons: 6,
      garconetes: 4,
      copeiros: 3,
      chefes: 2,
      outros: 7,
    },
    menu: {
      paraComecar: items(
        ["Canapé de queijo coalho com mel de engenho", "180", ""],
        ["Ceviche de tilápia em colher", "160", ""],
        ["Tartare de tomate com burrata", "140", "2 vegetarianos extras"],
        ["Welcome drink de caju e gengibre", "160", ""],
      ),
      amuseBouche: items(
        ["Ostra com granita de maracujá", "80", "Mesa dos noivos + VIP"],
        ["Crocante de tapioca com tartare", "160", ""],
      ),
      ramequim: items(
        ["Ramequim de camarão ao coco", "160", ""],
        ["Ramequim de palmito e castanha", "30", "Vegetariano"],
      ),
      menu: items(
        ["Filé mignon ao molho de vinho tinto", "90", ""],
        ["Robalo grelhado com manteiga de ervas", "70", ""],
        ["Nhoque de mandioquinha ao funghi", "30", "Vegetariano"],
      ),
      mesaBuffet: items(["Risoto de camarão com limão-cravo", "160", "Estação única"]),
      saladas: items(
        ["Salada tropical com manga e flor de sal", "160", ""],
        ["Carpaccio de abobrinha com pesto de castanha", "40", ""],
      ),
      altasHoras: items(["Mini hambúrguer e batata rústica", "80", "Após o bolo"]),
      sobremesas: items(
        ["Bolo de casamento — baunilha e frutas tropicais", "1", "Fornecedor parceiro"],
        ["Cheesecake de maracujá / petit gâteau", "160", ""],
      ),
      menuKids: items(
        ["Mini hambúrguer", "12", ""],
        ["Brigadeiro de colher", "24", ""],
      ),
      acompanhamentos: items(
        ["Arroz vermelho e legumes assados", "160", ""],
        ["Farofa de castanha de caju", "160", ""],
      ),
    },
    drinks: {
      agua: "10 cx",
      refrigerante: "8 cx",
      suco: "20 L",
    },
    uniforms: {
      dolma: { p: 0, m: 2, g: 3, gg: 1 },
      bata: { p: 1, m: 3, g: 2, gg: 0 },
      avental: { p: 2, m: 6, g: 8, gg: 2 },
    },
    logistics: {
      alcohol: "Espumante e vinho da casa. Open bar do cliente à parte.",
      materialPreviousDay: "sim",
      trestleTable: "sim",
      hasKitchen: "sim",
      hasFreezer: "sim",
      hasOven: "sim",
      hasMicrowave: "sim",
      flyingMenu: "nao",
    },
    dietaryNotes:
      "4 vegetarianos. 1 convidada celíaca (mesa 7, Paula Nunes). Sem amendoim. Tia da noiva alérgica a camarão — não circular risoto na mesa 4.",
    menuSetupNotes:
      "Risoto em dois turnos: 19h10 e 20h20. Filé malpassado na mesa dos noivos. Reservar 8 pratos vegetarianos extras. Chuva: cerimônia no salão.",
  }),
  createBlankEvent({
    ...stamp("evt-coffee-bnb", "CB-2026-0084", "2026-07-28T11:00:00.000Z"),
    title: "Coffee break — Encontro de Gestores BNB",
    type: "corporativo",
    status: "em_preparacao",
    date: "2026-08-25",
    materialDeliveryDate: "2026-08-25",
    foodDeliveryDate: "2026-08-25",
    perCapita: 80,
    venue: {
      kind: "externo",
      name: "Hotel Gran Marquise — Salão Iracema",
      address: "Av. Beira Mar, 3980 — Mucuripe, Fortaleza",
    },
    guests: { adults: 80, children: 0, professionals: 4 },
    teamArrival: "07:00",
    invitationTime: "08:30",
    serviceTime: "08:30",
    staff: {
      garcons: 3,
      garconetes: 1,
      copeiros: 1,
      chefes: 1,
      outros: 1,
    },
    menu: {
      paraComecar: items(
        ["Mini quiche de alho-poró", "80", ""],
        ["Wrap de frango desfiado", "80", ""],
        ["Tapioca recheada de queijo coalho", "80", ""],
      ),
      amuseBouche: [],
      ramequim: [],
      menu: [],
      mesaBuffet: items(["Frutas da estação", "80", ""]),
      saladas: [],
      altasHoras: [],
      sobremesas: items(["Bolo de rolo", "40", ""], ["Mini cuca de banana", "80", ""]),
      menuKids: [],
      acompanhamentos: [],
    },
    drinks: {
      agua: "6 cx",
      refrigerante: "",
      suco: "16 L",
    },
    uniforms: {
      dolma: { p: 0, m: 1, g: 1, gg: 0 },
      bata: { p: 0, m: 1, g: 0, gg: 0 },
      avental: { p: 0, m: 3, g: 2, gg: 0 },
    },
    logistics: {
      alcohol: "",
      materialPreviousDay: "nao",
      trestleTable: "nao",
      hasKitchen: "sim",
      hasFreezer: "sim",
      hasOven: "sim",
      hasMicrowave: "sim",
      flyingMenu: "nao",
    },
    dietaryNotes: "6 vegetarianos. 2 sem lactose.",
    menuSetupNotes: "Assar quiches no hotel. Levar forno auxiliar. Ilha única, reposição até 11h30.",
  }),
  createBlankEvent({
    ...stamp("evt-aniversario-zelia", "CB-2026-0082", "2026-07-02T16:20:00.000Z"),
    title: "Aniversário 60 anos — Zélia Mendes",
    type: "aniversario",
    status: "realizado",
    date: "2026-08-23",
    materialDeliveryDate: "2026-08-23",
    foodDeliveryDate: "2026-08-23",
    perCapita: 142,
    venue: {
      kind: "casa_braga",
      name: "Casa Braga",
      address: "Casa Braga — salão principal + varanda",
    },
    guests: { adults: 82, children: 8, professionals: 3 },
    teamArrival: "14:00",
    invitationTime: "19:00",
    serviceTime: "20:00",
    staff: {
      garcons: 4,
      garconetes: 2,
      copeiros: 2,
      chefes: 1,
      outros: 4,
    },
    menu: {
      paraComecar: items(
        ["Canapé de pasta de alcachofra", "90", ""],
        ["Mini esfirra de carne", "90", ""],
      ),
      amuseBouche: [],
      ramequim: [],
      menu: items(["Lasanha à bolonhesa", "90", ""], ["Strogonoff de frango", "90", ""]),
      mesaBuffet: items(["Mesa de frios e queijos", "90", ""]),
      saladas: items(["Salada verde", "90", ""]),
      altasHoras: [],
      sobremesas: items(["Bolo de chocolate com morango", "1", ""], ["Pudim de leite", "90", ""]),
      menuKids: items(["Nuggets e batata", "8", ""]),
      acompanhamentos: items(["Arroz de forno", "90", ""], ["Batata sauté", "90", ""]),
    },
    drinks: {
      agua: "4 cx",
      refrigerante: "6 cx",
      suco: "8 L",
    },
    uniforms: {
      dolma: { p: 0, m: 1, g: 1, gg: 0 },
      bata: { p: 0, m: 2, g: 1, gg: 0 },
      avental: { p: 1, m: 4, g: 3, gg: 0 },
    },
    logistics: {
      alcohol: "Cerveja e espumante do brinde.",
      materialPreviousDay: "nao",
      trestleTable: "nao",
      hasKitchen: "sim",
      hasFreezer: "sim",
      hasOven: "sim",
      hasMicrowave: "sim",
      flyingMenu: "nao",
    },
    dietaryNotes: "2 veganos — lasanha de berinjela reservada.",
    menuSetupNotes: "Buffet clássico. Bolo às 21h. Strogonoff em banho-maria baixo.",
  }),
  createBlankEvent({
    ...stamp("evt-brunch-domingo", "CB-2026-0085", "2026-08-04T09:00:00.000Z"),
    title: "Brunch de domingo na Casa",
    type: "social",
    status: "confirmado",
    date: "2026-08-24",
    materialDeliveryDate: "2026-08-24",
    foodDeliveryDate: "2026-08-24",
    perCapita: 0,
    venue: casaInternal(),
    guests: { adults: 40, children: 5, professionals: 0 },
    teamArrival: "08:00",
    invitationTime: "10:00",
    serviceTime: "10:00",
    staff: {
      garcons: 2,
      garconetes: 1,
      copeiros: 1,
      chefes: 1,
      outros: 1,
    },
    menu: {
      paraComecar: items(["Cesta de pães e geleias", "45", ""], ["Iogurte com granola e manga", "45", ""]),
      amuseBouche: [],
      ramequim: [],
      menu: items(["Ovos mexidos", "45", ""], ["Bacalhau à Braga", "45", ""], ["Tapioca de queijo", "45", ""]),
      mesaBuffet: [],
      saladas: items(["Salada de frutas", "45", ""]),
      altasHoras: [],
      sobremesas: items(["Bolo de milho", "45", ""], ["Torta de limão", "45", ""]),
      menuKids: items(["Panqueca com banana", "5", ""]),
      acompanhamentos: items(["Bacon e linguiça artesanal", "40", ""]),
    },
    drinks: {
      agua: "3 cx",
      refrigerante: "",
      suco: "10 L",
    },
    uniforms: {
      dolma: { p: 0, m: 1, g: 0, gg: 0 },
      bata: { p: 0, m: 1, g: 0, gg: 0 },
      avental: { p: 1, m: 2, g: 1, gg: 0 },
    },
    logistics: {
      alcohol: "Prosecco no brunch.",
      materialPreviousDay: "nao",
      trestleTable: "nao",
      hasKitchen: "sim",
      hasFreezer: "sim",
      hasOven: "sim",
      hasMicrowave: "sim",
      flyingMenu: "nao",
    },
    dietaryNotes: "3 sem glúten — pão de queijo separado.",
    menuSetupNotes: "Operação própria. Ovos em lotes pequenos.",
  }),
  createBlankEvent({
    ...stamp("evt-cha-clara", "CB-2026-0088", "2026-08-08T18:00:00.000Z"),
    title: "Chá de bebê — Clara Albuquerque",
    type: "social",
    status: "confirmado",
    date: "2026-08-30",
    materialDeliveryDate: "2026-08-30",
    foodDeliveryDate: "2026-08-30",
    perCapita: 84,
    venue: {
      kind: "externo",
      name: "Residência — Meireles",
      address: "Rua Silva Jatahy, 842 — Meireles, Fortaleza",
    },
    guests: { adults: 42, children: 8, professionals: 2 },
    teamArrival: "13:30",
    invitationTime: "16:00",
    serviceTime: "16:00",
    staff: {
      garcons: 2,
      garconetes: 1,
      copeiros: 1,
      chefes: 0,
      outros: 0,
    },
    menu: {
      paraComecar: items(
        ["Mini sanduíche de frango", "80", ""],
        ["Canapé de ricota com geleia de pimenta", "60", ""],
        ["Empada de palmito", "60", ""],
      ),
      amuseBouche: [],
      ramequim: [],
      menu: [],
      mesaBuffet: items(["Mesa de doces", "50", ""]),
      saladas: [],
      altasHoras: [],
      sobremesas: items(["Bem-casado e macaron", "50", ""], ["Bolo naked de baunilha", "1", ""]),
      menuKids: items(["Pipoca doce", "8", ""]),
      acompanhamentos: [],
    },
    drinks: {
      agua: "2 cx",
      refrigerante: "",
      suco: "8 L chá/limonada",
    },
    uniforms: {
      dolma: { p: 0, m: 0, g: 0, gg: 0 },
      bata: { p: 1, m: 2, g: 1, gg: 0 },
      avental: { p: 1, m: 2, g: 1, gg: 0 },
    },
    logistics: {
      alcohol: "",
      materialPreviousDay: "nao",
      trestleTable: "sim",
      hasKitchen: "nao",
      hasFreezer: "sim",
      hasOven: "nao",
      hasMicrowave: "sim",
      flyingMenu: "sim",
    },
    dietaryNotes: "1 alérgica a ovo — separar empadas.",
    menuSetupNotes: "Produção 90% na base. Sem fritura no apartamento. Encerrar até 19h.",
  }),
  createBlankEvent({
    ...stamp("evt-coquetel-joia", "CB-2026-0086", "2026-08-01T10:00:00.000Z"),
    title: "Coquetel de lançamento — Joalheria Lumen",
    type: "social",
    status: "em_preparacao",
    date: "2026-08-28",
    materialDeliveryDate: "2026-08-28",
    foodDeliveryDate: "2026-08-28",
    perCapita: 98,
    venue: {
      kind: "externo",
      name: "Iate Clube de Fortaleza — Espaço Náutico",
      address: "Av. Pres. Castelo Branco, 3333 — Mucuripe, Fortaleza",
    },
    guests: { adults: 100, children: 0, professionals: 6 },
    teamArrival: "16:00",
    invitationTime: "19:30",
    serviceTime: "19:30",
    staff: {
      garcons: 5,
      garconetes: 3,
      copeiros: 1,
      chefes: 1,
      outros: 2,
    },
    menu: {
      paraComecar: items(
        ["Atum selado com gergelim", "100", ""],
        ["Mini eclair de queijo de cabra", "100", ""],
        ["Espetinho de kafta", "100", ""],
      ),
      amuseBouche: items(["Ostra com granita de maracujá", "100", "Abrir às 18h50"]),
      ramequim: [],
      menu: [],
      mesaBuffet: [],
      saladas: [],
      altasHoras: [],
      sobremesas: items(["Brownie de chocolate 70%", "100", ""], ["Macaron de pistache", "100", ""]),
      menuKids: [],
      acompanhamentos: [],
    },
    drinks: {
      agua: "6 cx",
      refrigerante: "",
      suco: "detox — bar do clube",
    },
    uniforms: {
      dolma: { p: 0, m: 1, g: 1, gg: 0 },
      bata: { p: 0, m: 0, g: 0, gg: 0 },
      avental: { p: 0, m: 4, g: 6, gg: 0 },
    },
    logistics: {
      alcohol: "Bar do clube. Casa só gastronomia.",
      materialPreviousDay: "nao",
      trestleTable: "nao",
      hasKitchen: "sim",
      hasFreezer: "sim",
      hasOven: "nao",
      hasMicrowave: "sim",
      flyingMenu: "sim",
    },
    dietaryNotes: "Sem frutos do mar para 3 convidados VIP — lista com a assessoria.",
    menuSetupNotes: "Somente circulante. Passagem a cada 12 minutos. Vento na varanda — proteger ostras.",
  }),
  createBlankEvent({
    ...stamp("evt-feijoada", "CB-2026-0081", "2026-07-18T13:00:00.000Z"),
    title: "Feijoada de sábado",
    type: "social",
    status: "realizado",
    date: "2026-08-22",
    materialDeliveryDate: "2026-08-21",
    foodDeliveryDate: "2026-08-22",
    perCapita: 0,
    venue: casaInternal(),
    guests: { adults: 96, children: 14, professionals: 0 },
    teamArrival: "09:00",
    invitationTime: "12:00",
    serviceTime: "12:00",
    staff: {
      garcons: 4,
      garconetes: 2,
      copeiros: 2,
      chefes: 1,
      outros: 3,
    },
    menu: {
      paraComecar: items(["Torresmo e aipim", "110", ""]),
      amuseBouche: [],
      ramequim: [],
      menu: items(["Feijoada completa", "110", ""], ["Feijoada vegetariana", "12", "Rechaud separado"]),
      mesaBuffet: items(["Couve e laranja", "110", ""]),
      saladas: [],
      altasHoras: [],
      sobremesas: items(["Romeu e Julieta", "110", ""], ["Pudim de leite", "110", ""]),
      menuKids: items(["Arroz, feijão sem carne e farofa", "14", ""]),
      acompanhamentos: items(["Arroz branco, farofa e vinagrete", "110", ""]),
    },
    drinks: {
      agua: "6 cx",
      refrigerante: "8 cx",
      suco: "10 L",
    },
    uniforms: {
      dolma: { p: 0, m: 1, g: 1, gg: 0 },
      bata: { p: 0, m: 2, g: 1, gg: 0 },
      avental: { p: 2, m: 4, g: 4, gg: 1 },
    },
    logistics: {
      alcohol: "Caipirinha de caju e cerveja.",
      materialPreviousDay: "sim",
      trestleTable: "nao",
      hasKitchen: "sim",
      hasFreezer: "sim",
      hasOven: "sim",
      hasMicrowave: "sim",
      flyingMenu: "nao",
    },
    dietaryNotes: "Feijoada vegetariana identificada em rechaud separado.",
    menuSetupNotes: "Feijão no fogo desde sexta 22h. Repor laranja e couve às 13h30.",
  }),
  createBlankEvent({
    ...stamp("evt-formatura-ufc", "CB-2026-0091", "2026-08-10T15:00:00.000Z"),
    title: "Formatura Medicina UFC 2026.1",
    type: "social",
    status: "rascunho",
    date: "2026-09-05",
    materialDeliveryDate: "",
    foodDeliveryDate: "",
    perCapita: 0,
    venue: casaInternal("Salão + jardim. Palco no fundo do salão."),
    guests: { adults: 210, children: 10, professionals: 12 },
    teamArrival: "",
    invitationTime: "20:00",
    serviceTime: "",
    staff: emptyStaff(),
    menu: {
      paraComecar: items(["Canapés — cardápio B (a confirmar)", "", ""]),
      amuseBouche: [],
      ramequim: [],
      menu: items(["Opção A: estação de carnes", "", ""], ["Opção B: massa e risoto", "", ""]),
      mesaBuffet: [],
      saladas: [],
      altasHoras: [],
      sobremesas: [],
      menuKids: [],
      acompanhamentos: [],
    },
    drinks: {
      agua: "",
      refrigerante: "",
      suco: "",
    },
    dietaryNotes: "",
    menuSetupNotes: "Aguardando confirmação de pax e cardápio B até 25/08. Não produzir nada antes.",
  }),
  createBlankEvent({
    ...stamp("evt-jantar-unimed", "CB-2026-0090", "2026-08-06T09:30:00.000Z"),
    title: "Jantar corporativo — Unimed Fortaleza",
    type: "corporativo",
    status: "confirmado",
    date: "2026-09-12",
    materialDeliveryDate: "2026-09-12",
    foodDeliveryDate: "2026-09-12",
    perCapita: 267,
    venue: {
      kind: "externo",
      name: "Sede Unimed — Auditório Superior",
      address: "Av. Santos Dumont, 2626 — Aldeota, Fortaleza",
    },
    guests: { adults: 70, children: 0, professionals: 4 },
    teamArrival: "16:30",
    invitationTime: "20:00",
    serviceTime: "20:30",
    staff: {
      garcons: 6,
      garconetes: 2,
      copeiros: 1,
      chefes: 2,
      outros: 2,
    },
    menu: {
      paraComecar: items(["Amuse-bouche de abacaxi e queijo de coalho", "70", ""]),
      amuseBouche: items(["Tartare de atum com crispy de tapioca", "70", ""]),
      ramequim: [],
      menu: items(["Cordeiro com redução de caju", "70", "Ponto malpassado padrão"]),
      mesaBuffet: [],
      saladas: [],
      altasHoras: [],
      sobremesas: items(["Espuma de chocolate com flor de sal", "70", ""]),
      menuKids: [],
      acompanhamentos: items(["Purê de macaxeira e mini legumes", "70", ""]),
    },
    drinks: {
      agua: "4 cx",
      refrigerante: "",
      suco: "",
    },
    uniforms: {
      dolma: { p: 0, m: 2, g: 2, gg: 0 },
      bata: { p: 0, m: 0, g: 0, gg: 0 },
      avental: { p: 0, m: 4, g: 6, gg: 0 },
    },
    logistics: {
      alcohol: "Sommelier Unimed. Casa não leva álcool.",
      materialPreviousDay: "nao",
      trestleTable: "nao",
      hasKitchen: "sim",
      hasFreezer: "sim",
      hasOven: "nao",
      hasMicrowave: "sim",
      flyingMenu: "nao",
    },
    dietaryNotes: "2 sem frutos do mar — substituir entrada por carpaccio de abacaxi.",
    menuSetupNotes: "Três tempos empratados. 70 pratos em 8 minutos. Sem fritura no local.",
  }),
  createBlankEvent({
    ...stamp("evt-15-beatriz", "CB-2026-0092", "2026-08-14T17:40:00.000Z"),
    title: "15 anos — Beatriz Fontenele",
    type: "aniversario",
    status: "confirmado",
    date: "2026-09-19",
    materialDeliveryDate: "2026-09-18",
    foodDeliveryDate: "2026-09-19",
    perCapita: 153,
    venue: casaInternal("Salão principal. Pista no centro."),
    guests: { adults: 90, children: 50, professionals: 6 },
    teamArrival: "13:00",
    invitationTime: "19:30",
    serviceTime: "20:30",
    staff: {
      garcons: 5,
      garconetes: 3,
      copeiros: 2,
      chefes: 1,
      outros: 6,
    },
    menu: {
      paraComecar: items(["Salgados fritos e assados", "300", ""], ["Canapé doce de morango", "140", ""]),
      amuseBouche: [],
      ramequim: [],
      menu: items(["Penne ao molho branco", "140", ""], ["Frango grelhado com ervas", "140", ""]),
      mesaBuffet: items(["Mesa de frios", "140", ""], ["Mesa de doces finos", "140", ""]),
      saladas: [],
      altasHoras: items(["Hot dog e batata frita", "80", "Após o bolo"]),
      sobremesas: items(["Bolo de 15 anos", "1", ""]),
      menuKids: items(["Hot dog", "50", ""], ["Pipoca gourmet", "50", ""]),
      acompanhamentos: items(["Arroz e batata gratinada", "140", ""]),
    },
    drinks: {
      agua: "8 cx",
      refrigerante: "12 cx",
      suco: "16 L",
    },
    uniforms: {
      dolma: { p: 0, m: 1, g: 1, gg: 0 },
      bata: { p: 1, m: 2, g: 1, gg: 0 },
      avental: { p: 2, m: 6, g: 6, gg: 1 },
    },
    logistics: {
      alcohol: "Espumante do brinde.",
      materialPreviousDay: "sim",
      trestleTable: "sim",
      hasKitchen: "sim",
      hasFreezer: "sim",
      hasOven: "sim",
      hasMicrowave: "sim",
      flyingMenu: "nao",
    },
    dietaryNotes: "Criança alérgica a leite (mesa kids, Gael).",
    menuSetupNotes: "Pista ocupa 12 lugares. Separar lote kids sem lácteos.",
  }),
];

function casaInternal(extra = ""): EventRecord["venue"] {
  return {
    kind: "casa_braga",
    name: "Casa Braga",
    address: extra ? `Casa Braga — Fortaleza, CE. ${extra}` : "Casa Braga — Fortaleza, CE",
  };
}
